---
global:

  scrape_interval: 15s
  scrape_timeout: 5s

scrape_configs:

- job_name: app
  metrics_path: /metrics
  static_configs:
  - targets:
    - app:8080

- job_name: tempo
  metrics_path: /metrics
  static_configs:
  - targets:
    - tempo:3200
